apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iabu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iabu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-iabu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iabu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iabu
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-ugko-tenant/rhtap-demo-app/hacbs-test-project-iabu@sha256:218254b565a1c296eed26c418fa76afd1654d3606c46b0bbb5859678c2bd5743
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
